/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprogram_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	struct args  adicao_1_arg;
	float  *result_2;
	struct args  subtracao_1_arg;
	float  *result_3;
	struct args  multiplicacao_1_arg;
	float  *result_4;
	struct args  divisao_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, calcprogram, calcversion, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	adicao_1_arg.op1=1;
	adicao_1_arg.op2=3;

	result_1 = adicao_1(&adicao_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Resultado da Adicao: %f\n", *result_1);
	}

	subtracao_1_arg.op1 = 1;
	subtracao_1_arg.op2 = 2;

	result_2 = subtracao_1(&subtracao_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else{
	printf("Resultado da Subtracao: %f\n", *result_2);
}

	/*
	result_3 = multiplicacao_1(&multiplicacao_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = divisao_1(&divisao_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcprogram_1 (host);
exit (0);
}
