/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

float *
adicao_1_svc(struct args *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->op1 + argp->op2;

	return &result;
}

float *
subtracao_1_svc(struct args *argp, struct svc_req *rqstp)
{
	static float  result;

	 result = argp->op1 -argp->op2;
	return &result;
}

float *
multiplicacao_1_svc(struct args *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->op1 * argp->op2;

	return &result;
}

float *
divisao_1_svc(struct args *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->op1 / argp->op2;

	return &result;
}
