/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	float op1;
	float op2;
};
typedef struct args args;

#define calcprogram 0x21000000
#define calcversion 1

#if defined(__STDC__) || defined(__cplusplus)
#define adicao 1
extern  float * adicao_1(struct args *, CLIENT *);
extern  float * adicao_1_svc(struct args *, struct svc_req *);
#define subtracao 2
extern  float * subtracao_1(struct args *, CLIENT *);
extern  float * subtracao_1_svc(struct args *, struct svc_req *);
#define multiplicacao 3
extern  float * multiplicacao_1(struct args *, CLIENT *);
extern  float * multiplicacao_1_svc(struct args *, struct svc_req *);
#define divisao 4
extern  float * divisao_1(struct args *, CLIENT *);
extern  float * divisao_1_svc(struct args *, struct svc_req *);
extern int calcprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define adicao 1
extern  float * adicao_1();
extern  float * adicao_1_svc();
#define subtracao 2
extern  float * subtracao_1();
extern  float * subtracao_1_svc();
#define multiplicacao 3
extern  float * multiplicacao_1();
extern  float * multiplicacao_1_svc();
#define divisao 4
extern  float * divisao_1();
extern  float * divisao_1_svc();
extern int calcprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
