/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprogram_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	struct args  arg_1;
	int opcao;

#ifndef	DEBUG
	clnt = clnt_create (host, calcprogram, calcversion, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	do{
		printf("Digite a operacao desejada:\n 1 - adicao \n 2 - subtracao \n 3 - divisao \n 4 - multiplicacao \n 5 - sair\n");
		printf("Opcao: ");
		scanf("%i",&opcao);

		if ((opcao >=1) && (opcao<=4)){	
	
			printf("Digite o primeiro operador: ");
        	        scanf("%f",&arg_1.op1);
			printf("Digite o segundo operador: ");
	                scanf("%f",&arg_1.op2);		  
		
			switch (opcao){
				case 1:
					result_1 = soma_1(&arg_1, clnt);
					if (result_1 == (float *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					break;
				case 2:				
					result_1 = subtracao_1(&arg_1, clnt);
					if (result_1 == (float *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					break;
				case 3:					
					result_1 = divisao_1(&arg_1, clnt);
					if (result_1 == (float *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					break;
				case 4:	
					result_1 = multiplicacao_1(&arg_1, clnt);
					if (result_1 == (float *) NULL) {
						clnt_perror (clnt, "call failed");
					}
					break;
			}	
			printf("Resultado= %.2f\n",*result_1);
		}else if (opcao!=5)
			 printf("Opcao invalida\n");

		printf("-----------------------------------------------\n");

	}while (opcao != 5);	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcprogram_1 (host);
exit (0);
}
