/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"
#include <string.h>


#define TAM 50

char **
hello_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	
	result = (char *) malloc (TAM *sizeof(char));

	strcpy (result, "RPC: Hello World");	

	return &result;
}
