/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"
#include <string.h>


char **
hello_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	result = malloc(100*sizeof(char));
	strcpy(result,"RPC: servidor do joao");

	return &result;
}
