/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define helloprogram 0x20000000
#define helloversion 1

#if defined(__STDC__) || defined(__cplusplus)
#define hello 1
extern  char ** hello_1(void *, CLIENT *);
extern  char ** hello_1_svc(void *, struct svc_req *);
extern int helloprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define hello 1
extern  char ** hello_1();
extern  char ** hello_1_svc();
extern int helloprogram_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
